import type { Metadata } from 'next';
import QueryProvider from './provider';
import '@/styles/style.scss';
import Header from '@/components/layout/Header';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <QueryProvider>
          <Header />
          <main className="main">{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
